### ISSUE TITLE
documentation: how can we extract the emission parameters from a model?

### ISSUE THREAD

**Issue by murphyk** [lindermanlab/ssm-jax-refactor#19]
In https://github.com/lindermanlab/ssm-jax-refactor/blob/main/notebooks/bernoulli-hmm-example.ipynb, you create an HMM with random bernoulli observation model. How can I extract and plot the underlying `nstates x ndims` matrix of probabilities? (It's buried behind some TFP class.)

Similarly, in https://github.com/lindermanlab/ssm-jax-refactor/blob/main/notebooks/gaussian-hmm-example.ipynb, how do I  extract the observation parameters of the learned model.

**Comment by slinderman** [comment]
Good call. Just added convenience getters to https://github.com/lindermanlab/ssm-jax-refactor/blob/main/ssm/hmm/models.py

The commit is a mess due to a sloppy merge on my part, but the changes are in here: https://github.com/lindermanlab/ssm-jax-refactor/commit/b872d337795a153ad59ed47e992873c173de0b29
